apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: fack-ju-toaster-testrun
  namespace: default
spec:
  parallelism: 5
  script:
    configMap:
      name: k6-tests
      file: ukadwebsite-direct.js
  arguments:  --tag testid=megasupertest --out experimental-prometheus-rw
  runner:
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://prometheus-stack-kube-prom-prometheus.observability.svc.cluster.local:9090/api/v1/write


